version: '2'

services:
    web:
          image: nginx:alpine
          ports:
              - "8888:80"
              - "443:443"
          volumes:
              - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          volumes_from:
              - app
          links:
              - app

    app:
            build: ./docker/php
            volumes:
                - ./src:/var/www/html
            expose:
                - "9000"

    postgres:
            build: ./docker/postgres
            volumes:
                - ./docker/postgres/data/:/var/lib/postgresql/data
            ports:
                - "5432:5432"
            environment:
                POSTGRES_DB: ${POSTGRES_DB}
                POSTGRES_USER: ${POSTGRES_USER}
                POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}